<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

	<ItemGroup>
	    <AvaloniaResource Include="Java.xshd" />
	    <AvaloniaResource Include="Styles/**"/>
	</ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.12"/>
        <PackageReference Include="Avalonia.AvaloniaEdit" Version="11.4.1"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.3.12"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.12"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.12"/>
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.12">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="LibGit2Sharp" Version="0.31.0" />
        <PackageReference Include="MsBox.Avalonia" Version="3.0.0-rc2"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1"/>
        <PackageReference Include="Octokit" Version="14.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\StartWindow.axaml.cs">
        <DependentUpon>StartWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\WorkerWindow.axaml.cs">
        <DependentUpon>WorkerWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\AdminWindow.axaml.cs">
        <DependentUpon>MainWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\NewProjectWindow.axaml.cs">
        <DependentUpon>NewProjectWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UserControls\MainControls\AppMainControl.axaml.cs">
        <DependentUpon>AppMainControl.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UserControls\MainControls\WorkerPanelControl.axaml.cs">
        <DependentUpon>AppPanelControl.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>
</Project>
